# SPDX-License-Identifier: GPL-3.0-only
# Cross compilation only. Native execution is not supported by this file.
if(NOT DEFINED ENV{OO_PS4_TOOLCHAIN})
    message(FATAL_ERROR "Carga ~/.config/xcloud4/env.sh antes de configurar")
endif()
set(X4_SDK "$ENV{OO_PS4_TOOLCHAIN}")
set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-freebsd12-elf)
set(CMAKE_SYSROOT "${X4_SDK}")
set(CMAKE_C_FLAGS_INIT "-fPIC -isystem ${X4_SDK}/include")
set(CMAKE_CXX_FLAGS_INIT "-fPIC -nostdinc++ -isystem ${X4_SDK}/include/c++/v1 -isystem ${X4_SDK}/include")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH "${X4_SDK}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
